# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))

todo_include_todos=True

# -- Project information -----------------------------------------------------

project = '準同型表探索による関数計算ライブラリ基本設計書'
copyright = 'Copyright 2018 Yamana Laboratory, Waseda University'
author = '株式会社エデュアム'

# The full version, including alpha/beta/rc tags
release = '1.2'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
import sphinx_fontawesome
extensions = ['sphinx_fontawesome', 'sphinx.ext.todo', 'recommonmark']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'ja'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
#html_theme = 'alabaster'

import sphinx_rtd_theme
html_theme = "sphinx_rtd_theme"
html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']



# -- Setting for markdown ----------------------------------------------------

source_suffix = ['.rst', '.md']

from recommonmark.parser import CommonMarkParser

source_parsers = {
    '.md': CommonMarkParser,
}

from recommonmark.transform import AutoStructify

github_doc_root = 'https://github.com/rtfd/recommonmark/tree/master/doc/'
def setup(app):
    app.add_config_value('recommonmark_config', {
            'url_resolver': lambda url: github_doc_root + url,
            'auto_toc_tree_section': 'Contents',
            }, True)
    app.add_transform(AutoStructify)


# -- Setting for LaTex --------------------------------------------------------



latex_docclass = {'manual': 'jsbook'}

numfig = True
numfig_format = {'section': '%s',
                 'figure': 'Fig %s',
                 'table': 'Table %s',
                 'code-block': 'List %s'};

# delete empty pages
#latex_elements = {'extraclassoptions': 'openany'}

latex_elements = {
    'extraclassoptions': 'openany',
    'preamble': r'''
\makeatletter
\renewcommand{\sphinxmaketitle}{
\vspace*{\stretch{1}}
\begin{center}
    {\LARGE \@title}
\end{center}
\vspace{\stretch{2}}
\begin{center}
    {\em\large\py@HeaderFamily \py@release\releaseinfo} \par
    \vspace{20pt}
    {\large
    \@date \par
    \@author \par
    \vspace{50pt}
    } \par
\end{center}
}
'''
}
