#ifndef FTS_DEFINE_HPP
#define FTS_DEFINE_HPP

#define FTS_TIMEOUT_SEC (60)
#define FTS_RETRY_INTERVAL_USEC (2000000)

#define FTS_DEFAULT_MAX_CONCURRENT_QUERIES 128
#define FTS_DEFAULT_MAX_RESULTS 128
#define FTS_DEFAULT_MAX_RESULT_LIFETIME_SEC 50000

#define FTS_LUTFILE_EXT "csv"

#define FTS_LUT_POSSIBLE_INPUT_NUM_ONE (819200)
#define FTS_LUT_POSSIBLE_INPUT_NUM_TWO (4096)

#endif /* FTS_DEFINE_HPP */
