name: build_documents

on: push

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
        architecture: x64
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx commonmark recommonmark sphinx_rtd_theme sphinx_fontawesome
        sudo apt -y install \
             texlive-latex-recommended \
             texlive-latex-extra \
             texlive-fonts-recommended \
             texlive-fonts-extra \
             texlive-lang-japanese \
             texlive-lang-cjk \
             latexmk
    - name: build basic spec
      run: |
        cd doc/spec-ja
        make latexpdf
    - name: upload basic spec
      uses: actions/upload-artifact@v1
      with:
        name: fhe-table-search_basic-spec
        path: doc/spec-ja/build/latex/sphinx.pdf
